version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Crucial: This allows your local IDE to connect to Kafka!
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"


  authservice:
    image: authservice
    container_name: authservice
    ports:
      - '9898:9898'
    environment:
        KAFKA_HOST: kafka
        KAFKA_PORT: 9092
        MYSQL_HOST: mysql
        MYSQL_PORT: 3306
        MYSQL_DB: authservice
    depends_on:
       - kafka
       - mysql
  userservice:
    image: userservice
    container_name: userservice
    ports:
      - '9810:9810'

    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
    depends_on:
      - kafka
      - mysql
  expenceservice:
    image: expenceservice
    container_name: expenceservice
    ports:
      - '9820:9820'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expense_db
    depends_on:
      - kafka
      - mysql

  smsservice:
    image: smsservice
    container_name: smsservice
    env_file:
      - ../.env
    ports:
      - '8081:8081'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expense_db
      gemini_api : ${gemini_api}
    depends_on:
        - kafka
        - mysql
        - expenceservice
        - userservice