version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
        - zookeeper
    ports:
        - "29092:29092" # External port for your local IDE
    environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        # IMPORTANT: Dual Listeners Setup
        KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"


  authservice:
    image: auth_service
    container_name: auth_service
    ports:
      - '9898:9898'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: auth_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

  userservice:
    image: user_service
    container_name: user_service
    ports:
      - '9810:9810'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: userservice
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy

  smsservice:
   image: sms_service
   container_name: sms_service
   env_file:
     - ../.env
   ports:
     - '8081:8081'
   environment:
    KAFKA_HOST: kafka
    KAFKA_PORT: 9092
    MYSQL_HOST: mysql
    MYSQL_PORT: 3306
    MYSQL_DB: expense_db
    gemini_api: ${gemini_api}
   depends_on:
    kafka:
      condition: service_healthy
    mysql:
      condition: service_healthy
    expenceservice:
      condition: service_started
    userservice:
      condition: service_started

  expenceservice:
    image: expense_service
    container_name: expense_service
    ports:
      - '9820:9820'
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: expense_db
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy